apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  rules:
  - host: 9f52aa809ee442d68abf.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 8080
status:
  loadBalancer: {}
