kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-server-storage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: nginx-server-storage
    spec:
      containers:
      - name: nginx-server-storage
        image: andyzhangx/nginx-server:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        volumeMounts:
        - name: azuredisk
          mountPath: /mnt/azuredisk		
        - name: azurefile
          mountPath: /mnt/azurefile
        - name: hostpath
          mountPath: /mnt/hostpath
        - name: blobfuse
          mountPath: /mnt/blobfuse          
      volumes:
      - name: azurefile
        persistentVolumeClaim:
          claimName: pvc-azurefile
      - name: azuredisk
        persistentVolumeClaim:
          claimName: pvc-azuredisk
      - name: hostpath
        hostPath:
          path: /mnt
      - name: blobfuse
        flexVolume:
          driver: "azure/blobfuse"
          readOnly: false
          secretRef:
            name: blobfusecreds
          options:
            container: public         
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server-storage
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx-server-storage
