version: '3'
services:
    netbox:
        image: rleastusacr.azurecr.io/netbox:v2
        depends_on:
        - postgres
        env_file: netbox.env
        volumes:
        - ./startup_scripts:/opt/netbox/startup_scripts:ro
        - ./initializers:/opt/netbox/initializers:ro
        - ./configuration:/etc/netbox/config:ro
        - netbox-nginx-config:/etc/netbox-nginx/
        - netbox-static-files:/opt/netbox/netbox/static
        - netbox-media-files:/opt/netbox/netbox/media
        - netbox-report-files:/etc/netbox/reports:ro
    nginx:
        image: nginx:1.13-alpine
        command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
        depends_on:
        - netbox
        ports:
        - 8080
        volumes:
        - netbox-static-files:/opt/netbox/netbox/static:ro
        - netbox-nginx-config:/etc/netbox-nginx/:ro
    postgres:
        image: postgres:10.5-alpine
        env_file: postgres.env
        volumes:
        - netbox-postgres-data:/var/lib/postgresql/data
    redis:
        image: redis:4-alpine
        hostname: redis
        env_file: redis.env
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
        - netbox-redis-data:/data

volumes:
    netbox-static-files:
        driver: local
    netbox-nginx-config:
        driver: local
    netbox-media-files:
        driver: local
    netbox-report-files:
        driver: local
    netbox-postgres-data:
        driver: local
    netbox-redis-data:
        driver: local
