[environments]
  [environments.development]
    name = "netbox"
    namespace = "netbox"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = "charts/netbox/Chart.yaml"
