apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netbox
  namespace: netbox
  labels:
    app: netbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netbox
    spec:
      containers:
      - name: netbox
        image: ninech/netbox:v2.2.6
        ports:
        - containerPort: 8001
        env:
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              key: ALLOWED_HOSTS
              name: netbox-env
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: netbox-env
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: netbox-env
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: netbox-env
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: netbox-env
        - name: EMAIL_FROM
          valueFrom:
            secretKeyRef:
              key: EMAIL_FROM
              name: netbox-env
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: EMAIL_PASSWORD
              name: netbox-env
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              key: EMAIL_PORT
              name: netbox-env
        - name: EMAIL_SERVER
          valueFrom:
            secretKeyRef:
              key: EMAIL_SERVER
              name: netbox-env
        - name: EMAIL_TIMEOUT
          valueFrom:
            secretKeyRef:
              key: EMAIL_TIMEOUT
              name: netbox-env
        - name: EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              key: EMAIL_USERNAME
              name: netbox-env
        - name: NETBOX_PASSWORD
          valueFrom:
            secretKeyRef:
              key: NETBOX_PASSWORD
              name: netbox-env
        - name: NETBOX_USERNAME
          valueFrom:
            secretKeyRef:
              key: NETBOX_USERNAME
              name: netbox-env
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY
              name: netbox-env
        - name: SUPERUSER_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: SUPERUSER_API_TOKEN
              name: netbox-env
        - name: SUPERUSER_EMAIL
          valueFrom:
            secretKeyRef:
              key: SUPERUSER_EMAIL
              name: netbox-env
        - name: SUPERUSER_NAME
          valueFrom:
            secretKeyRef:
              key: SUPERUSER_NAME
              name: netbox-env
        - name: SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SUPERUSER_PASSWORD
              name: netbox-env
        volumeMounts:
        - name: netbox-nginx-config
          mountPath: /etc/netbox-nginx/ 
        - name: netbox-static-files
          mountPath: /opt/netbox/netbox/static  
      restartPolicy: Always
      volumes:
      - name: netbox-nginx-config
        configMap:
          name: nginx-conf
      - name: netbox-static-files
        persistentVolumeClaim:
          claimName: netbox-static-files

---
apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: netbox
  labels:
    app: netbox
spec:
  ports:
  - name: nbox
    port: 8001
    targetPort: 8001
  selector:
    app: netbox

      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-static-files
  namespace: netbox
  labels:
    pvcname: netbox-static-files
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-conf
  namespace: netbox
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      tcp_nopush     on;
      keepalive_timeout  65;
      gzip  on;
      server_tokens off;
      server {
          listen 80;
          server_name localhost;
          access_log off;
          location /static/ {
            alias /opt/netbox/netbox/static/;
          }
          location / {
            proxy_pass http://netbox:8001;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
          }
      }
    }


