apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: netbox
  labels:
    backend: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        backend: postgres
    spec:
      containers:  
      - image: postgres:9.6-alpine
        name: postgres 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: postgres-env
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres-env      
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-env
          
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: netbox
  labels:
    backend: postgres
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 5432
    targetPort: 5432
  selector:
    backend: postgres

