{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: netbox.hearst.com
    http:
      paths:
      - path: /
        backend:
          serviceName: netbox
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
