kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-csi-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-hostpath
  resources:
    requests:
      storage: 1Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-csi-hostpath
spec:
  containers:
   - name: nginx-csi-hostpath
     image: nginx
     volumeMounts:
       - mountPath: /data
         name: csi-hostpath
  volumes:
   - name: csi-hostpath
     persistentVolumeClaim:
       claimName: pvc-csi-hostpath
       readOnly: false

