apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    diskName: test.vhd
    diskURI: https://someaccount.blob.microsoft.net/vhds/test.vhd
