apiVersion: v1
kind: Pod
metadata:
 name: nginx-azurefile
spec:
 containers:
  - image: nginx
    name: nginx-azurefile
    volumeMounts:
      - name: azure
        mountPath: /mnt/azurefile
 volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: k8stest
          readOnly: false
