apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: k8stest
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pv-azurefile  
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azurefile
spec:
  containers:
  - image: nginx
    name: nginx-azurefile
    command:
    - "/bin/sh"
    - "-c"
    - while true; do echo $(date) >> /mnt/azurefile/outfile; sleep 1; done
    volumeMounts:
    - name: azurefile01
      mountPath: "/mnt/azurefile"
  volumes:
  - name: azurefile01
    persistentVolumeClaim:
      claimName: pvc-azurefile
