---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-azurefile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-azurefile
    spec:
      containers:
      - name: deployment-azurefile
        image: nginx
        command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/blobfile/outfile; sleep 1; done		
        volumeMounts:
        - name: blobfile01
          mountPath: "/mnt/blobfile"
      volumes:
      - name: blobfile01
        persistentVolumeClaim:
          claimName: pvc-azurefile
